/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AuthenticatedFichesRouteImport } from './routes/_authenticated/fiches'
import { Route as AuthenticatedGlossaireRouteImport } from './routes/_authenticated/glossaire'
import { Route as AuthenticatedMesFichesRouteImport } from './routes/_authenticated/mes-fiches'
import { Route as AuthenticatedOutilsRouteImport } from './routes/_authenticated/outils'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedOutilsIndexRouteImport } from './routes/_authenticated/outils.index'
import { Route as AuthenticatedOutilsSlugRouteImport } from './routes/_authenticated/outils.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichesRoute = AuthenticatedFichesRouteImport.update({
  id: '/fiches',
  path: '/fiches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGlossaireRoute = AuthenticatedGlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesFichesRoute = AuthenticatedMesFichesRouteImport.update({
  id: '/mes-fiches',
  path: '/mes-fiches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutilsRoute = AuthenticatedOutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutilsIndexRoute =
  AuthenticatedOutilsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOutilsRoute,
  } as any)
const AuthenticatedOutilsSlugRoute = AuthenticatedOutilsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedOutilsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/fiches': typeof AuthenticatedFichesRoute
  '/glossaire': typeof AuthenticatedGlossaireRoute
  '/mes-fiches': typeof AuthenticatedMesFichesRoute
  '/outils': typeof AuthenticatedOutilsRouteWithChildren
  '/studio': typeof AuthenticatedStudioRoute
  '/outils/$slug': typeof AuthenticatedOutilsSlugRoute
  '/outils/': typeof AuthenticatedOutilsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/fiches': typeof AuthenticatedFichesRoute
  '/glossaire': typeof AuthenticatedGlossaireRoute
  '/mes-fiches': typeof AuthenticatedMesFichesRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/outils/$slug': typeof AuthenticatedOutilsSlugRoute
  '/outils': typeof AuthenticatedOutilsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/_authenticated/fiches': typeof AuthenticatedFichesRoute
  '/_authenticated/glossaire': typeof AuthenticatedGlossaireRoute
  '/_authenticated/mes-fiches': typeof AuthenticatedMesFichesRoute
  '/_authenticated/outils': typeof AuthenticatedOutilsRouteWithChildren
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/outils/$slug': typeof AuthenticatedOutilsSlugRoute
  '/_authenticated/outils/': typeof AuthenticatedOutilsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bibliotheque'
    | '/fiches'
    | '/glossaire'
    | '/mes-fiches'
    | '/outils'
    | '/studio'
    | '/outils/$slug'
    | '/outils/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bibliotheque'
    | '/fiches'
    | '/glossaire'
    | '/mes-fiches'
    | '/studio'
    | '/outils/$slug'
    | '/outils'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bibliotheque'
    | '/_authenticated/fiches'
    | '/_authenticated/glossaire'
    | '/_authenticated/mes-fiches'
    | '/_authenticated/outils'
    | '/_authenticated/studio'
    | '/_authenticated/outils/$slug'
    | '/_authenticated/outils/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiches': {
      id: '/_authenticated/fiches'
      path: '/fiches'
      fullPath: '/fiches'
      preLoaderRoute: typeof AuthenticatedFichesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/glossaire': {
      id: '/_authenticated/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof AuthenticatedGlossaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-fiches': {
      id: '/_authenticated/mes-fiches'
      path: '/mes-fiches'
      fullPath: '/mes-fiches'
      preLoaderRoute: typeof AuthenticatedMesFichesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outils': {
      id: '/_authenticated/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof AuthenticatedOutilsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outils/': {
      id: '/_authenticated/outils/'
      path: '/'
      fullPath: '/outils/'
      preLoaderRoute: typeof AuthenticatedOutilsIndexRouteImport
      parentRoute: typeof AuthenticatedOutilsRoute
    }
    '/_authenticated/outils/$slug': {
      id: '/_authenticated/outils/$slug'
      path: '/$slug'
      fullPath: '/outils/$slug'
      preLoaderRoute: typeof AuthenticatedOutilsSlugRouteImport
      parentRoute: typeof AuthenticatedOutilsRoute
    }
  }
}

interface AuthenticatedOutilsRouteChildren {
  AuthenticatedOutilsSlugRoute: typeof AuthenticatedOutilsSlugRoute
  AuthenticatedOutilsIndexRoute: typeof AuthenticatedOutilsIndexRoute
}

const AuthenticatedOutilsRouteChildren: AuthenticatedOutilsRouteChildren = {
  AuthenticatedOutilsSlugRoute: AuthenticatedOutilsSlugRoute,
  AuthenticatedOutilsIndexRoute: AuthenticatedOutilsIndexRoute,
}

const AuthenticatedOutilsRouteWithChildren =
  AuthenticatedOutilsRoute._addFileChildren(AuthenticatedOutilsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedFichesRoute: typeof AuthenticatedFichesRoute
  AuthenticatedGlossaireRoute: typeof AuthenticatedGlossaireRoute
  AuthenticatedMesFichesRoute: typeof AuthenticatedMesFichesRoute
  AuthenticatedOutilsRoute: typeof AuthenticatedOutilsRouteWithChildren
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedFichesRoute: AuthenticatedFichesRoute,
  AuthenticatedGlossaireRoute: AuthenticatedGlossaireRoute,
  AuthenticatedMesFichesRoute: AuthenticatedMesFichesRoute,
  AuthenticatedOutilsRoute: AuthenticatedOutilsRouteWithChildren,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
